name: Generate Snake

# Controls when the action will run
on:
  schedule:
    # Runs every 6 hours
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v2

      # Step 2: Generate the snake animation
      - name: Generate Snake
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: liam-007
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Step 3: Push the changes to the output branch
      - name: Push changes to output branch
        uses: actions/checkout@v2
        with:
          ref: output

      - name: Copy files to the output branch
        run: |
          mkdir -p dist
          cp dist/github-contribution-grid-snake.* $GITHUB_WORKSPACE

      - name: Push changes
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add dist/github-contribution-grid-snake.*
          git commit -m "Generated snake animation" || echo "No changes to commit"
          git push origin output

      # Step 4: Deploy the output to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
